function compile(varargin)
%% History
%  2008-04-01: Added check for pre Matlab 2006b for non-large dim 
%              sparse matrices.
%%

debug = 0; if strmatch('-debug',varargin), debug=1; end
verbose = 0; if strmatch('-verbose',varargin), verbose=1; end
clear mex

mbglfiles = {%'astar_search_mex.c', 'bfs_mex.c', 'dfs_mex.c', 'biconnected_components_mex.c', ...
         'components_mex.c', 'matlab_bgl_sp_mex.c', ...
         %'matlab_bgl_all_sp_mex.c', ...
         %'mst_mex.c', 'clustering_coefficients_mex.c', ...
         %'betweenness_centrality_mex.c', ...
         %'max_flow_mex.c', ...
         %'bfs_dfs_vis_mex.c', ...
         %'topological_order_mex.c', ...
         %'matching_mex.c', ...
         %'core_numbers_mex.c', ...
         %'dominator_tree_mex.c', ...
         %'test_matching_mex.c', ...
         %'path_from_pred_mex.c', ...
         %'kamada_kawai_spring_layout_mex.c', ...
         %'fruchterman_reingold_mex.c', ...
         %'gursoy_atun_mex.c', ...
         %'planar_test_mex.c', 'planar_edges_mex.c', 'planar_drawing_mex.c'
         };
     

options = {'-O', '-v'};

for file = mbglfiles

     mex(options{:},['-I', 'libmbgl/include'], char(file));  
     %mexstr = ['mex ' mexflags ' ' char(file)];
     %fprintf('%s\n', mexstr);
     %eval(mexstr);
end;

